### ISSUE TITLE
Ajouter le tuto "Tout sur les variables" de Joke

### ISSUE THREAD

**Issue by aureliendossantos** [gamedevalliance/wiki.gamedevalliance.fr#61]
Ce tuto a apparemment été très populaire et a aidé de nombreuses personnes. Il faudrait le remettre au goût du jour (donc focus sur VXA et MV) et refaire les images.

http://www.biloucorp.com/tout-tout-tout-sur-les-variables--partie-1-2-6

**Comment by GoulvenC** [comment]
Cette isssue ne correspond plus à la direction du wiki actuelle.
Une partie de son contenu correspond davantage à [fairedesjeux.fr](https://github.com/gamedevalliance/fairedesjeux.fr), le reste devrait être réadapté dans une direction plus encyclopédique.

En attendant de mieux documenter cette nouvelle direction et d'y adapter cette issue, je la close.
