### ISSUE TITLE
Affichage mobile du retour à l'accueil

### ISSUE THREAD

**Issue by aureliendossantos** [gamedevalliance/wiki.gamedevalliance.fr#91]
Sur mobile, le bouton "Retour vers l'accueil du portail" ne suit pas l'alternance gris clair/gris foncé du sommaire.

![Screenshot](https://i.imgur.com/cA6LXaX.png)

**Comment by GoulvenC** [comment]
Le wiki est actuellement en cours de refonte, notamment graphique, dans la branch `redesign`, il est inutile de passer du temps sur des bugs liés à l'ancien design. Issue closed.
